FROM python:version
RUN apt-get update && \
    apt-get install git -y && \
    python -m pip install git+https://github.com/ersilia-os/ersilia-pack.git
COPY docker-entrypoint.sh /root/docker-entrypoint.sh
RUN chmod + /root/docker-entrypoint.sh
EXPOSE 80
ENTRYPOINT [ "sh", "/root/docker-entrypoint.sh"]