FROM ersiliaos/ersiliapack-VERSION:latest
ARG MODEL=eos_identifier
ENV MODEL=$MODEL
WORKDIR /root
COPY ./$MODEL /root/$MODEL
RUN mkdir /root/bundles && ersilia_model_pack --repo_path $MODEL --bundles_repo_path /root/bundles && \
    rm -rf /root/$MODEL && rm -rf /root/.cache && \
    cp /root/bundles/$MODEL/*/information.json /root/information.json && \
    cp /root/bundles/$MODEL/*/api_schema.json /root/api_schema.json && \
    cp /root/bundles/$MODEL/*/status.json /root/status.json