name: Batch Template
description: Create a new Batch
title: "[Batch 🐕]: "
assignees:
  - DhanshreeA,miquelduranfrigola,GemmaTuron
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Summarize the batch in 1-4 sentences. Include the problem(s) we're tying to solve and proposed solution(s). Can this be solved in a few days?"
    validations:
      required: true
  - type: textarea
    id: objectives
    attributes:
      label: Objective(s)
      description: "What are the key objective(s) and goals for this batch?"
  - type: textarea
    id: resources
    attributes:
      label: Documentation
      description: "Add links to any documentention, resources, tools or designs"
      
