name: Epic Template
description: Create a new Initiative, Epic or Batch
title: "[Epic 🐅]:"
assignees:
  - DhanshreeA,miquelduranfrigola,GemmaTuron
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Summarize the epic. Include the problem(s) we're tying to solve and proposed solution(s)."
  - type: textarea
    id: objectives
    attributes:
      label: Objective(s)
      description: "What are the key objective(s) and goals for this epic?"
  - type: textarea
    id: resources
    attributes:
      label: Documentation
      description: "Add links to any documentention, resources, tools or designs"
      
