name:  🐈 Task
description: Create a new Task
title: "🐈 Task: "
assignees:
  - DhanshreeA
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Summarize the task in 1-4 sentences. Include the problem(s) we're tying to solve and proposed solution(s). Can be resolved in a few hours?"
    validations:
      required: true
  - type: textarea
    id: objectives
    attributes:
      label: Objective(s)
      description: "What are the key objective(s) and goals for this task?"
  - type: textarea
    id: resources
    attributes:
      label: Documentation
      description: "Add links to any documentention, resources, tools or designs"
      
