FROM python:3.7-slim-buster

WORKDIR /root
ARG BUILD_MODEL
ENV PATH=$PATH:/usr/bin/conda/bin
COPY download-miniconda.sh /root/download-miniconda.sh
COPY docker-entrypoint.sh /root/docker-entrypoint.sh
COPY nginx.conf /etc/nginx/sites-available/default
RUN chmod + /root/download-miniconda.sh
RUN bash /root/download-miniconda.sh

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]

# Set an environment variable to keep the bash running
ENV KEEP_RUNNING_IN_FOREGROUND "tail -f /dev/null"

# When the container launches, run bash
CMD ["/bin/bash"]