name: Approve Command Trigger Bot
on:
  issue_comment:
    types: [created]
jobs:
  approve-command-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PK }}
      - name: Approve Command Trigger
        uses: peter-evans/slash-command-dispatch@2afb49dbaafaba8005860648bf7fc178637aca0d # pin@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          issue-type: issue
          permission: write
          reactions: false
          commands: |
            approved
