name: Deploy and test ersilia with miniconda

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Source conda
        run: |
         source $CONDA/etc/profile.d/conda.sh
      - name: Install dependencies
        run: |
         source activate
         conda init
         conda install git-lfs -c conda-forge
         git-lfs install
         conda install gh -c conda-forge
      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install -e .[test]
      - name: Deploy models
        run: |
          source activate
          ersilia fetch molecular-weight
          echo "Serving molecular-weight model."
          ersilia serve molecular-weight
          ersilia api calculate -i "CC(=O)OC1=CC=CC=C1C(=O)O"|grep "180.15899"
      - name: Run pytest
        run: |
          source activate          
          pip install pytest
          echo "pytest"
          pytest
