# Single workflow to increment ersilia version in pyproject.toml,
# tag and push the commit to the repository, release to GitHub, PyPI, Conda, and DockerHub
# upload_ersilia_base_to_dockerhub
# upload_ersilia_installer_to_dockerhub:

name: Ersilia Release, Ersilia Base Image to Dockerhub, Ersilia Installer to Dockerhub

on:
  workflow_dispatch: # run manually
  schedule:
    - cron: ' 0 3 1 * *' # run at 3:00 AM on the first day of the month
  
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
    steps:

      - name: Checkout persist credentials
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v3.5.3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
      - name: Increment package version
        id: version
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/static_version_writer.py
          echo "VERSION=$(python static_version_writer.py)" >> "$GITHUB_OUTPUT"
          rm static_version_writer.py
      
      - name: Create a release tag
        id: tag
        run: |
          git config --local user.email "ersilia-bot@users.noreply.github.com"
          git config --local user.name "ersilia-bot"
          git tag -a "v${{ steps.version.outputs.VERSION }}" -m "v${{ steps.version.outputs.VERSION }}"

      - name: Commit and push changes done to the static version file and pyproject.toml
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # pin@v1.5
        with:
          author_name: "ersilia-bot"
          author_email: "ersilia-bot@users.noreply.github.com"
          message: "update version [skip ci]"
          repository: "ersilia-os/${{ github.event.repository.name }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          amend: true
          force: true
          branch: "master"

  gh-release:
    runs-on: ubuntu-latest
    needs: version
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create GitHub release
        id: gh_release
        run: |
          # Get the version file that we updated in the previous job
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/ersilia/_static_version.py

          month=$(date +'%B')
          year=$(date +'%Y')
          title="Release $month $year"
          version=`sed -n 's/.*version = "\([^"]*\)".*/\1/p' _static_version.py`
          gh release create "v$version" --title "$title" --notes-from-tag

  pypi-release:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # pin@v5.1.0
        with:
          python-version: '3.8'
          # cache: 'pip' # caching pip dependencies

      - name: Get version
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/ersilia/_static_version.py
          mv _static_version.py ersilia/.

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v3.0.0
            
      - name: Build and publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

        run: |
          poetry config -- http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
          poetry --build publish 


  upload_ersilia_base_to_dockerhub:
    strategy:
      matrix:
        build-version: ["v1", "v2"]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # log in to dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout persist credentials
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Get version
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/ersilia/_static_version.py
          mv _static_version.py ersilia/.

      - name: Copy Dockerfile to base directory
        run: |
          cp dockerfiles/model-deploy-${{ matrix.build-version }}/base/* .
            
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ersiliaos/base-${{ matrix.build-version }} 
          # Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}


  upload_ersilia_installer_to_dockerhub:
    runs-on: ubuntu-latest
    needs: dockerhub-upload-base
    steps:
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # log in to dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout persist credentials
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Get version
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/ersilia/_static_version.py
          mv _static_version.py ersilia/.

      - name: Copy Dockerfile to base directory
        run: |
          cp dockerfiles/installer/Dockerfile .
          cp -r dockerfiles/installer/required_files .
          cp dockerfiles/installer/download-miniconda.sh .
            
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ersiliaos/shell
          # Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
