# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_run:
    workflows: ["Tag to version"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # pin@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # pin@v4.7.0
        with:
          python-version: '3.7'
          # cache: 'pip' # caching pip dependencies

      - name: Get version
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/ersilia/_static_version.py
          mv _static_version.py ersilia/.

      - name: Install Poetry
        run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            source $HOME/.poetry/env
            echo `poetry --version`
            echo "Poetry successfully installed"

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

        run: |
          source $HOME/.poetry/env
          poetry build
          twine upload --verbose --skip-existing dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD
