# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_run:
    workflows: ["Tag to version"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # pin@v5.0.0
        with:
          python-version: '3.7'
          # cache: 'pip' # caching pip dependencies

      - name: Get version
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/ersilia/_static_version.py
          mv _static_version.py ersilia/.

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.4.0
            
      - name: Build and publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

        run: |
          poetry config -- http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
          poetry --build publish 
