name: Quick model test (Manual)
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      model_id:
        description: Model ID
        required: true
        type: string

permissions:
  contents: read

env:
  MODEL_ID: ${{ github.event.inputs.model_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # pin@v3.5.3

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh

      - name: Set Python to 3.10.10
        run:
         conda install -y python=3.10.10

      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge

      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install -e .[test]

      - name: Predict output
        run: |
          source activate
          echo "Sample model id selected: $MODEL_ID"
          ersilia -v fetch $MODEL_ID
          ersilia -v serve $MODEL_ID
          ersilia sample -n 5 -f input.csv
          ersilia -v api -i input.csv
          ersilia close

      - name: Upload log output
        if: ${{ failure() }}
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # pin@v4.3.1
        with:
          name: ersilia-predict-logs
          path: /home/runner/eos/console.log
