name: Tag to version

on:
  push:
    tags:
      - 'v*'
  
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout persist credentials
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # pin@v3.5.3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Make a change and commit
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/static_version_writer.py
          python static_version_writer.py
          rm static_version_writer.py

      - name: Commit and push changes done to the static version file
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # pin@v1.5
        with:
          author_name: "ersilia-bot"
          author_email: "ersilia-bot@users.noreply.github.com"
          message: "update version [skip ci]"
          repository: "ersilia-os/${{ github.event.repository.name }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          amend: true
          force: true
          branch: "master"
