name: Tag to version

on:
  push:
    tags:
      - 'v*'
  
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout persist credentials
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # pin@v3.5.3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Make a change and commit
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/static_version_writer.py
          python static_version_writer.py
          rm static_version_writer.py

      - name: Commit and push changes done to the static version file
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772 # pin@v1.4
        with:
          author_name: "ersilia-bot"
          author_email: "ersilia-bot@users.noreply.github.com"
          message: "update version [skip ci]"
          repository: "ersilia-os/${{ github.event.repository.name }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          amend: true
          force: true
          branch: "master"
