name: Run PyTest

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v3.5.3

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh
        
      - name: Set Python to 3.10.10
        run:
         conda install -y python=3.10.10  

      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge

      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install -e .[test]

      - name: Run pytest
        run: |
          source activate          
          pip install pytest
          pytest

  update_model_request:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Check for changes in tag.txt
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "ersilia/hub/content/metadata/tag.txt"; then
            echo "Tag file modified"
            echo "modified=true" >> $GITHUB_ENV
          else
            echo "Tag file not modified"
            echo "modified=false" >> $GITHUB_ENV
          fi

      - name: Run update_model_request script
        if: env.modified == 'true'
        run: |
          source activate
          python .github/scripts/update_model_request.py

      - name: Commit and push changes
        if: env.modified == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/issue_template/model_request.yml
          git commit -m "Update model request template with sorted tags"
          git push
