name: Run PyTest

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v3.5.3

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh
        
      - name: Set Python to 3.10.10
        run:
         conda install -y python=3.10.10  

      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge

      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install -e .[test]

      - name: Run pytest
        run: |
          source activate          
          pip install pytest
          pytest

  update-model-request_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Path Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            tag-file:
              - 'ersilia/hub/content/metadata/tag.txt'

      - name: Set up Python
        if: steps.filter.outputs.tag-file == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: steps.filter.outputs.tag-file == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run update_model_request_template.py
        if: steps.filter.outputs.tag-file == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/update_model_request_template.py

      - name: Commit and push changes
        if: steps.filter.outputs.tag-file == 'true'
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # pin@v1.5
        with:
          author_name: "ersilia-bot"
          author_email: "ersilia-bot@users.noreply.github.com"
          message: "Update model_request.yml with new tags from tag.txt"
          directory: .
          repository: "ersilia-os/ersilia"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
