name: Metadata update

on:
  workflow_dispatch:

jobs:
  update-metadata:
    strategy:
      matrix:
        model-id: ["eos9gg2", "eos80ch", "eos8fma"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: run script
        id: run-script
        env:
          MODEL_ID: ${{ matrix.model-id }}
          USER_NAME: ${{ github.repository_owner }}
          BRANCH: "main"
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          pip install .
          pip install requests pyairtable
          echo "Updating metadata to AirTable"
          python3 .github/scripts/airtableops.py airtable-update --user $USER_NAME --repo $MODEL_ID --branch $BRANCH --api-key $AIRTABLE_API_KEY
          rm airtableops.py
  
